### ISSUE TITLE
"save stream" broken on edit stream

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-angular-frontend#3]
/stream/xxxxxx/edit
(change title …)
Click "save stream"
… says "saving", but never finishes

```
TypeError: Cannot set property 'uuid' of undefined
    at Object.actions.update (http://192.168.56.101:8080/js/piecemeta-angular-frontend.min.js:3:22437)
    at l.async.waterfall.a.submit (http://192.168.56.101:8080/js/piecemeta-angular-frontend.min.js:3:17711)
    at ib.functionCall (http://192.168.56.101:8080/js/piecemeta-angular-dependencies.min.js:199:303)
    at Dc.(anonymous function).compile.d.on.f (http://192.168.56.101:8080/js/piecemeta-angular-dependencies.min.js:215:485)
    at l.$get.l.$eval (http://192.168.56.101:8080/js/piecemeta-angular-dependencies.min.js:126:305)
    at l.$get.l.$apply (http://192.168.56.101:8080/js/piecemeta-angular-dependencies.min.js:127:6)
    at HTMLFormElement.<anonymous> (http://192.168.56.101:8080/js/piecemeta-angular-dependencies.min.js:216:36)
    at HTMLFormElement.c (http://192.168.56.101:8080/js/piecemeta-angular-dependencies.min.js:33:389)
```

**Comment by dasantonym** [comment]
fixed and pushed
